repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3.10
        args: [ --max-line-length=120 ]
        stages: [ commit, push ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3.10
        stages: [ commit, push ]
