version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: ./compose/db/Dockerfile
    ports:
      - "5437:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "students" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 3s
  test-db:
    build:
      context: .
      dockerfile: ./compose/db/Dockerfile
    ports:
      - "5438:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${TEST_POSTGRES_DB}" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 3s
  web:
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
